services:
  app1:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.app1
      args:
        - IMAGE_TAG=${PHP_IMAGE_TAG}
    container_name: app-1
    volumes:
      - ./app1:/var/www/html:rw
      - ./config/phpcs.xml.example:/var/www/html/phpcs.xml.dist
      - ./config/phpstan.neon.example:/var/www/html/phpstan.neon

  app1db:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.app1.db
      args:
        - IMAGE_TAG=${POSTGRES_IMAGE_TAG}
    environment:
      - POSTGRES_PASSWORD=${APP1_POSTGRES_PASSWORD}
      - POSTGRES_USER=${APP1_POSTGRES_USER}
      - POSTGRES_DB=${APP1_POSTGRES_DB}
    ports:
      - ${APP1_POSTGRES_PORT}:5432
    container_name: app-1-db
