api.users.create:
  path: /api/users
  methods: POST
  controller: App\Core\CreateUser\CreateUserController::create

api.users.get:
  path: /api/users/{id}
  methods: GET
  controller: App\Core\GetUser\GetUserController::get

api.users.update:
  path: /api/users/{id}
  methods: PATCH
  controller: App\Core\UpdateUser\UpdateUserController::update
